name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v4

      - name: Instalar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar Dependências
        run: pip install -q -r requirements-dev.txt

      - name: Rodar os testes
        run: pytest libpythonpro/

      - name: Rodar o flake8
        run: flake8