name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os aruivos do repositorio
        uses: actions/checkout@v4.1.0

      - name: Roda outro Comando
        run: echo $(ls)
